// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdSDl10Tq008d5JHd-EaFShm5miyuL2h0',
    appId: '1:976891141785:web:61ffa0ee4292245891a208',
    messagingSenderId: '976891141785',
    projectId: 'redlink-d7c6f',
    authDomain: 'redlink-d7c6f.firebaseapp.com',
    storageBucket: 'redlink-d7c6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbc4dZtKYpRQ0tED64iSwiIUh0COSRv3k',
    appId: '1:976891141785:android:6824db9199e3b0ab91a208',
    messagingSenderId: '976891141785',
    projectId: 'redlink-d7c6f',
    storageBucket: 'redlink-d7c6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9V9Re0Gxu-PJKUttE1CcV5LtJqhhed9U',
    appId: '1:976891141785:ios:f62555c7970f825591a208',
    messagingSenderId: '976891141785',
    projectId: 'redlink-d7c6f',
    storageBucket: 'redlink-d7c6f.firebasestorage.app',
    iosBundleId: 'com.example.redLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9V9Re0Gxu-PJKUttE1CcV5LtJqhhed9U',
    appId: '1:976891141785:ios:f62555c7970f825591a208',
    messagingSenderId: '976891141785',
    projectId: 'redlink-d7c6f',
    storageBucket: 'redlink-d7c6f.firebasestorage.app',
    iosBundleId: 'com.example.redLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdSDl10Tq008d5JHd-EaFShm5miyuL2h0',
    appId: '1:976891141785:web:cbd0f5c29598ccb091a208',
    messagingSenderId: '976891141785',
    projectId: 'redlink-d7c6f',
    authDomain: 'redlink-d7c6f.firebaseapp.com',
    storageBucket: 'redlink-d7c6f.firebasestorage.app',
  );
}
